package cn.dtkeys.dataservice.audit;

/**
 * 平台基础审计动作。
 */
public enum AuditAction {
    VIEW_PLATFORM_BASELINE,
    EXECUTE_DATA_SERVICE_QUERY,
    VIEW_AUDIT_LOG_LIST,
    VIEW_AUDIT_LOG_DETAIL,
    CREATE_CONNECTION,
    UPDATE_CONNECTION,
    ENABLE_CONNECTION,
    DISABLE_CONNECTION,
    TEST_CONNECTION,
    DELETE_CONNECTION,
    CREATE_SERVICE,
    UPDATE_SERVICE,
    PUBLISH_SERVICE,
    DISABLE_SERVICE,
    DELETE_SERVICE,
    SAVE_FEDERATED_SQL_DRAFT,
    PREVIEW_FEDERATED_SQL,
    UPDATE_SOURCE_CAPABILITY
}
